#include "Utils/InputUtils.h"

const char* InputUtils::MouseInputActionToString(EInputAction inputAction) {
    switch (inputAction) {
        case EInputAction::RELEASE:
            return "RELEASE";
        case EInputAction::PRESS:
            return "PRESS";
        case EInputAction::REPEAT:
            return "REPEAT";
    }
    return "ERROR";
}

const char* InputUtils::InputKeyToString(EInputKey inputKey) {
    switch (inputKey) {
        case EInputKey::MOUSE_LEFT:
            return "MOUSE_LEFT";
        case EInputKey::MOUSE_RIGHT:
            return "MOUSE_RIGHT";
        case EInputKey::MOUSE_MIDDLE:
            return "MOUSE_MIDDLE";
        case EInputKey::MOUSE_BUTTON_4:
            return "MOUSE_BUTTON_4";
        case EInputKey::MOUSE_BUTTON_5:
            return "MOUSE_BUTTON_5";
        case EInputKey::MOUSE_BUTTON_6:
            return "MOUSE_BUTTON_6";
        case EInputKey::MOUSE_BUTTON_7:
            return "MOUSE_BUTTON_7";
        case EInputKey::SPACE:
            return "SPACE";
        case EInputKey::APOSTROPHE:
            return "APOSTROPHE";
        case EInputKey::COMMA:
            return "COMMA";
        case EInputKey::MINUS:
            return "MINUS";
        case EInputKey::PERIOD:
            return "PERIOD";
        case EInputKey::SLASH:
            return "SLASH";
        case EInputKey::KEY_0:
            return "KEY_0";
        case EInputKey::KEY_1:
            return "KEY_1";
        case EInputKey::KEY_2:
            return "KEY_2";
        case EInputKey::KEY_3:
            return "KEY_3";
        case EInputKey::KEY_4:
            return "KEY_4";
        case EInputKey::KEY_5:
            return "KEY_5";
        case EInputKey::KEY_6:
            return "KEY_6";
        case EInputKey::KEY_7:
            return "KEY_7";
        case EInputKey::KEY_8:
            return "KEY_8";
        case EInputKey::KEY_9:
            return "KEY_9";
        case EInputKey::SEMICOLON:
            return "SEMICOLON";
        case EInputKey::EQUAL:
            return "EQUAL";
        case EInputKey::A:
            return "A";
        case EInputKey::B:
            return "B";
        case EInputKey::C:
            return "C";
        case EInputKey::D:
            return "D";
        case EInputKey::E:
            return "E";
        case EInputKey::F:
            return "F";
        case EInputKey::G:
            return "G";
        case EInputKey::H:
            return "H";
        case EInputKey::I:
            return "I";
        case EInputKey::J:
            return "J";
        case EInputKey::K:
            return "K";
        case EInputKey::L:
            return "L";
        case EInputKey::M:
            return "M";
        case EInputKey::N:
            return "N";
        case EInputKey::O:
            return "O";
        case EInputKey::P:
            return "P";
        case EInputKey::Q:
            return "Q";
        case EInputKey::R:
            return "R";
        case EInputKey::S:
            return "S";
        case EInputKey::T:
            return "T";
        case EInputKey::U:
            return "U";
        case EInputKey::V:
            return "V";
        case EInputKey::W:
            return "W";
        case EInputKey::X:
            return "X";
        case EInputKey::Y:
            return "Y";
        case EInputKey::Z:
            return "Z";
        case EInputKey::LEFT_BRACKET:
            return "LEFT_BRACKET";
        case EInputKey::BACKSLASH:
            return "BACKSLASH";
        case EInputKey::RIGHT_BRACKET:
            return "RIGHT_BRACKET";
        case EInputKey::GRAVE_ACCENT:
            return "GRAVE_ACCENT";
        case EInputKey::WORLD_1:
            return "WORLD_1";
        case EInputKey::WORLD_2:
            return "WORLD_2";
        case EInputKey::ESCAPE:
            return "ESCAPE";
        case EInputKey::ENTER:
            return "ENTER";
        case EInputKey::TAB:
            return "TAB";
        case EInputKey::BACKSPACE:
            return "BACKSPACE";
        case EInputKey::INSERT:
            return "INSERT";
        case EInputKey::DELETE:
            return "DELETE";
        case EInputKey::RIGHT:
            return "RIGHT";
        case EInputKey::LEFT:
            return "LEFT";
        case EInputKey::DOWN:
            return "DOWN";
        case EInputKey::UP:
            return "UP";
        case EInputKey::PAGE_UP:
            return "PAGE_UP";
        case EInputKey::PAGE_DOWN:
            return "PAGE_DOWN";
        case EInputKey::HOME:
            return "HOME";
        case EInputKey::END:
            return "END";
        case EInputKey::CAPS_LOCK:
            return "CAPS_LOCK";
        case EInputKey::SCROLL_LOCK:
            return "SCROLL_LOCK";
        case EInputKey::NUM_LOCK:
            return "NUM_LOCK";
        case EInputKey::PRINT_SCREEN:
            return "PRINT_SCREEN";
        case EInputKey::PAUSE:
            return "PAUSE";
        case EInputKey::F1:
            return "F1";
        case EInputKey::F2:
            return "F2";
        case EInputKey::F3:
            return "F3";
        case EInputKey::F4:
            return "F4";
        case EInputKey::F5:
            return "F5";
        case EInputKey::F6:
            return "F6";
        case EInputKey::F7:
            return "F7";
        case EInputKey::F8:
            return "F8";
        case EInputKey::F9:
            return "F9";
        case EInputKey::F10:
            return "F10";
        case EInputKey::F11:
            return "F11";
        case EInputKey::F12:
            return "F12";
        case EInputKey::F13:
            return "F13";
        case EInputKey::F14:
            return "F14";
        case EInputKey::F15:
            return "F15";
        case EInputKey::F16:
            return "F16";
        case EInputKey::F17:
            return "F17";
        case EInputKey::F18:
            return "F18";
        case EInputKey::F19:
            return "F19";
        case EInputKey::F20:
            return "F20";
        case EInputKey::F21:
            return "F21";
        case EInputKey::F22:
            return "F22";
        case EInputKey::F23:
            return "F23";
        case EInputKey::F24:
            return "F24";
        case EInputKey::F25:
            return "F25";
        case EInputKey::KP_0:
            return "KP_0";
        case EInputKey::KP_1:
            return "KP_1";
        case EInputKey::KP_2:
            return "KP_2";
        case EInputKey::KP_3:
            return "KP_3";
        case EInputKey::KP_4:
            return "KP_4";
        case EInputKey::KP_5:
            return "KP_5";
        case EInputKey::KP_6:
            return "KP_6";
        case EInputKey::KP_7:
            return "KP_7";
        case EInputKey::KP_8:
            return "KP_8";
        case EInputKey::KP_9:
            return "KP_9";
        case EInputKey::KP_DECIMAL:
            return "KP_DECIMAL";
        case EInputKey::KP_DIVIDE:
            return "KP_DIVIDE";
        case EInputKey::KP_MULTIPLY:
            return "KP_MULTIPLY";
        case EInputKey::KP_SUBTRACT:
            return "KP_SUBTRACT";
        case EInputKey::KP_ADD:
            return "KP_ADD";
        case EInputKey::KP_ENTER:
            return "KP_ENTER";
        case EInputKey::KP_EQUAL:
            return "KP_EQUAL";
        case EInputKey::LEFT_SHIFT:
            return "LEFT_SHIFT";
        case EInputKey::LEFT_CONTROL:
            return "LEFT_CONTROL";
        case EInputKey::LEFT_ALT:
            return "LEFT_ALT";
        case EInputKey::LEFT_SUPER:
            return "LEFT_SUPER";
        case EInputKey::RIGHT_SHIFT:
            return "RIGHT_SHIFT";
        case EInputKey::RIGHT_CONTROL:
            return "RIGHT_CONTROL";
        case EInputKey::RIGHT_ALT:
            return "RIGHT_ALT";
        case EInputKey::RIGHT_SUPER:
            return "RIGHT_SUPER";
        case EInputKey::MENU:
            return "MENU";
        default:
            break;
    }
    return "ERROR";
}

bool InputUtils::IsMouseInput(EInputKey key) {
    switch (key) {
        case EInputKey::MOUSE_LEFT:
            return true;
        case EInputKey::MOUSE_RIGHT:
            return true;
        case EInputKey::MOUSE_MIDDLE:
            return true;
        case EInputKey::MOUSE_BUTTON_4:
            return true;
        case EInputKey::MOUSE_BUTTON_5:
            return true;
        case EInputKey::MOUSE_BUTTON_6:
            return true;
        case EInputKey::MOUSE_BUTTON_7:
            return true;
        case EInputKey::SPACE:
            return false;
        case EInputKey::APOSTROPHE:
            return false;
        case EInputKey::COMMA:
            return false;
        case EInputKey::MINUS:
            return false;
        case EInputKey::PERIOD:
            return false;
        case EInputKey::SLASH:
            return false;
        case EInputKey::KEY_0:
            return false;
        case EInputKey::KEY_1:
            return false;
        case EInputKey::KEY_2:
            return false;
        case EInputKey::KEY_3:
            return false;
        case EInputKey::KEY_4:
            return false;
        case EInputKey::KEY_5:
            return false;
        case EInputKey::KEY_6:
            return false;
        case EInputKey::KEY_7:
            return false;
        case EInputKey::KEY_8:
            return false;
        case EInputKey::KEY_9:
            return false;
        case EInputKey::SEMICOLON:
            return false;
        case EInputKey::EQUAL:
            return false;
        case EInputKey::A:
            return false;
        case EInputKey::B:
            return false;
        case EInputKey::C:
            return false;
        case EInputKey::D:
            return false;
        case EInputKey::E:
            return false;
        case EInputKey::F:
            return false;
        case EInputKey::G:
            return false;
        case EInputKey::H:
            return false;
        case EInputKey::I:
            return false;
        case EInputKey::J:
            return false;
        case EInputKey::K:
            return false;
        case EInputKey::L:
            return false;
        case EInputKey::M:
            return false;
        case EInputKey::N:
            return false;
        case EInputKey::O:
            return false;
        case EInputKey::P:
            return false;
        case EInputKey::Q:
            return false;
        case EInputKey::R:
            return false;
        case EInputKey::S:
            return false;
        case EInputKey::T:
            return false;
        case EInputKey::U:
            return false;
        case EInputKey::V:
            return false;
        case EInputKey::W:
            return false;
        case EInputKey::X:
            return false;
        case EInputKey::Y:
            return false;
        case EInputKey::Z:
            return false;
        case EInputKey::LEFT_BRACKET:
            return false;
        case EInputKey::BACKSLASH:
            return false;
        case EInputKey::RIGHT_BRACKET:
            return false;
        case EInputKey::GRAVE_ACCENT:
            return false;
        case EInputKey::WORLD_1:
            return false;
        case EInputKey::WORLD_2:
            return false;
        case EInputKey::ESCAPE:
            return false;
        case EInputKey::ENTER:
            return false;
        case EInputKey::TAB:
            return false;
        case EInputKey::BACKSPACE:
            return false;
        case EInputKey::INSERT:
            return false;
        case EInputKey::DELETE:
            return false;
        case EInputKey::RIGHT:
            return false;
        case EInputKey::LEFT:
            return false;
        case EInputKey::DOWN:
            return false;
        case EInputKey::UP:
            return false;
        case EInputKey::PAGE_UP:
            return false;
        case EInputKey::PAGE_DOWN:
            return false;
        case EInputKey::HOME:
            return false;
        case EInputKey::END:
            return false;
        case EInputKey::CAPS_LOCK:
            return false;
        case EInputKey::SCROLL_LOCK:
            return false;
        case EInputKey::NUM_LOCK:
            return false;
        case EInputKey::PRINT_SCREEN:
            return false;
        case EInputKey::PAUSE:
            return false;
        case EInputKey::F1:
            return false;
        case EInputKey::F2:
            return false;
        case EInputKey::F3:
            return false;
        case EInputKey::F4:
            return false;
        case EInputKey::F5:
            return false;
        case EInputKey::F6:
            return false;
        case EInputKey::F7:
            return false;
        case EInputKey::F8:
            return false;
        case EInputKey::F9:
            return false;
        case EInputKey::F10:
            return false;
        case EInputKey::F11:
            return false;
        case EInputKey::F12:
            return false;
        case EInputKey::F13:
            return false;
        case EInputKey::F14:
            return false;
        case EInputKey::F15:
            return false;
        case EInputKey::F16:
            return false;
        case EInputKey::F17:
            return false;
        case EInputKey::F18:
            return false;
        case EInputKey::F19:
            return false;
        case EInputKey::F20:
            return false;
        case EInputKey::F21:
            return false;
        case EInputKey::F22:
            return false;
        case EInputKey::F23:
            return false;
        case EInputKey::F24:
            return false;
        case EInputKey::F25:
            return false;
        case EInputKey::KP_0:
            return false;
        case EInputKey::KP_1:
            return false;
        case EInputKey::KP_2:
            return false;
        case EInputKey::KP_3:
            return false;
        case EInputKey::KP_4:
            return false;
        case EInputKey::KP_5:
            return false;
        case EInputKey::KP_6:
            return false;
        case EInputKey::KP_7:
            return false;
        case EInputKey::KP_8:
            return false;
        case EInputKey::KP_9:
            return false;
        case EInputKey::KP_DECIMAL:
            return false;
        case EInputKey::KP_DIVIDE:
            return false;
        case EInputKey::KP_MULTIPLY:
            return false;
        case EInputKey::KP_SUBTRACT:
            return false;
        case EInputKey::KP_ADD:
            return false;
        case EInputKey::KP_ENTER:
            return false;
        case EInputKey::KP_EQUAL:
            return false;
        case EInputKey::LEFT_SHIFT:
            return false;
        case EInputKey::LEFT_CONTROL:
            return false;
        case EInputKey::LEFT_ALT:
            return false;
        case EInputKey::LEFT_SUPER:
            return false;
        case EInputKey::RIGHT_SHIFT:
            return false;
        case EInputKey::RIGHT_CONTROL:
            return false;
        case EInputKey::RIGHT_ALT:
            return false;
        case EInputKey::RIGHT_SUPER:
            return false;
        case EInputKey::MENU:
            return false;
        default:
            break;
    }

    return false;
}